= IDE pre Lua

Pre vývoj Lua modulov je možné použiť https://code.visualstudio.com/[Visual Studio Code],
https://studio.zerobrane.com/[ZeroBrane Studio] a vyvíjať lokálne alebo v Docker kontajneri.
Odporúčame použiť Visual Studio Code, najmä kvôli použitiu docker-u a prostredia zhodného s CI.

== Visual Studio Code

==== Príprava repozitárov a kontajnera

Na disku na ľubovoľné miesto naklonujeme repozitár `devenv` a inicializujeme submoduly.
Submoduly jednotlivých submodulov (teda závislosti lua modulov) nie je potrebne sťahovať,
pretože niektoré sú nainštalované v image a zvyšné ako submoduly devenv repozitára.
Následne vytvoríme image a spustíme kontajner.

[source,bash]
----
git clone git@gitlab.com:FIIT/Common/devenv.git
cd devenv
git submodule update --init --remote
docker-compose run --service-ports --name luadev luadev

----

Kontajer stačí vytvoriť len raz, neskôr je možné ho jednoducho spustiť `docker start -i luadev`.
Ak potrebujeme image a kontajner vytvoriť nanovo, spustíme:

[source,bash]
----
docker-compose down
docker-compose build --no-cache
docker-compose run --service-ports --name luadev luadev
----

V každom repozitári by mal byť priečinok `dev` so súbormi `lrdb_debug.lua` a `start_debug.sh`.
Ak ho niektorý neobsahuje, skopírujeme ho z develop vetvy, prípadne iného repozitára.
Táto ukážka je pre použitie `luadb`, podstatné sú prvé dva riadky, kde sa akivuje debugger.

[source,lua hl_lines="1 2"]
----
lrdb = require("lrdb_server")
lrdb.activate(21110)

astManager = require "luadb.manager.AST"
extractor  = require "luadb.extraction.extractor"
path = "src"

astMan = astManager.new()
extractedGraph = extractor.extract(path, astMan)

lrdb.deactivate()
----

==== Nastavenie IDE

Do IDE nainštalujeme rozšírenie LRDB debugger nachádzajúce sa v repozitári `devenv`.
Je možné ho nainštalovať príkazom `code --install-extension lrdb-0.3.5.vsix`
alebo manuálne vo VS Code cez Extensions -&gt; More Actions… -&gt; Install from VSIX.
Nakoniec v IDE otvoríme priečinok `luadev` osahujúci všetky repozitáre.

==== Spustenie

Súbor `lrdb_debug.lua` slúži ako 'main', kde je ukážkové použitie danej knižnice.
Pri vývoji používame tento súbor ako pre vyvolanie vyvíjanej funkcionality,
ale zmeny v ňom necommitujeme. Pre jeho spustenie vykonáme príkaz `bash dev/start_debug.sh`.
V tomto bash skripte sa cyklicky vykonáva `lua lrdb_debug.lua`, teda nie je potrebné
ho vždy manuálne spúšťať. Ukončenie skriptu sa realizuje štandardne pomocou Ctrl+C.

* !!! tip "Tip"
** Pri debugovaní používame ako pracovný adresár samotný repozitár,
 teda napríklad `cd /luadev/luadb`

Po spustení `lrdb_debug.lua` je vykonávanie pozastavené a čaká na pripojenie IDE.
Pre pripojenie vo VS Code stlačíme klávesu F5.

== ZeroBrane Studio

ZeroBrane Studio je oveľa jednoduchšie na nastavenie ako VSCode,
avšak doposiaľ sa nám v ňom nepodarilo spojazdniť remote-debugging.
Taktiež je VSCode uživateľsky oveľa prívetivejšie prostredie na prácu.
Z týchto dôvodov odporúčame použiť skôr VSCode a teda postup popísaný vyššie.
Takisto je treba poznamenať, že v tomto IDE je možné debugovať len jazyk LUA, nie TERRA.

==== Nastavenie IDE

Štandardne je IDE nastavené tak, že pri debugovaní je potrebné mať otvorené všetky súbory,
do ktorých môže program počas behu vojsť. Preto musíme pred začatím nastaviť IDE tak,
aby volané moduly otváralo automaticky. Toto spravíme v
`Menu =&gt; Edit =&gt; Preferences =&gt; Settings: User`. Otvorí sa nám konfiguračný súbor
`user.lua`, do ktorého na nový riadok pridáme príkaz

----
editor.autoactivate = true
----

a následne zmeny uložíme a môžme súbor zavrieť. Týmto je IDE pripravené na debuggovanie.