= 游늵 UML diagramy

== Motiv치cia

Pou쮂셨ate programu by mal ma콘 mo쬹os콘 zobrazi콘 si r칪zne metriky a UML diagramy analyzovan칠ho k칩du.
Dva z치kladn칠 diagramy, ktor칠 chceme generova콘 s칰 Class diagram a Sequence diagram.

== N치vod na pou쬴tie

. na캜칤tame graf moonscript projektu (link:../prirucky/pouzivatelska_prirucka/moonscript_projekty.adoc[n치vod])
. my코ou ozna캜칤me triedu (캜erven치) alebo met칩du (zelen치)
. stla캜칤me kl치vesu 5

== Technick치 dokument치cia

V aktu치lnom stave je mo쬹칠 generova콘 Class diagram a Sequence diagram pre Moonscript k칩dy.
Implement치cia je realizovan치 v module `luameg` a v lua 캜asti 3D Softvizu
(`App/main.lua` a `softviz/graph_handler`).

=== Luameg

Modul `luameg.plantuml` exportuje pr칤slu코n칠 funkcie pre generovanie Class a Sequence
diagramov bu캞 v plantuml txt alebo priamo svg.
Pri generovan칤 rekurz칤vne preh쬬d치va graf od zvolen칠ho uzla a generuje plantuml textov칳 s칰bor.
N치sledne je spusten칳 `plantuml.jar` s t칳mto textov칳m s칰borom na vstupe a vygeneruje svg s칰bor.
Obsah svg s칰boru je na캜칤tan칳 do premennej, s칰bory odstr치nen칠 a hodota navr치ten치.

Pre zobrazenie grafu s칰 generovan칠 uzly `method_sequenceDiagram` a `class_ClassDiagram`.
Tieto uzly sl칰쬴a pre layoutovanie, aby boli vhodne umiestnen칠 v priestore.

=== Lua 캜as콘 3DSoftVizu

V `App/main.lua` s칰 dve funkcie pre generovanie Class a Sequence diagramov.
Ako argument maj칰 id grafu a id uzla. Ak je tento uzol typu `method_sequenceDiagram`
alebo `class_ClassDiagram`, vyh쬬d치 sa k nim prisl칰chaj칰ci `class`/`method` uzol.
Nasleduje volanie rovnomennej funkcie v `graph_handler`-i, v ktorom je referencia na graf.

=== Unity

Unity obsahuje webov칳 prehliada캜 `ZFBrowser`, v ktorom sa UML diagramy zobrazuj칰.
Hlavn치 trieda, ktor치 obsluhuje tento prehliada캜 je `BrowsersManager`, ktor치 vyh쬬d치va
vy코코ie spom칤nan칠 layoutovacie uzly a pre 켿e in코tanciuje pr칤slu코n칠 prehliada캜e.
Prehliada캜e s칰 spo캜iatku skryt칠, zobrazia sa po ozna캜en칤 pr칤slu코neho uzla a stla캜en칤
캜칤selnej kl치vesy 1 a 5, pre UML diagramy to je pr치ve kl치vesa 5.

Ka쬯칳 typ prehliada캜a m치 svoj 'skript', ktor칳 obsluhuje svoju in코tanciu `ZFBrowser`-a
a prefabu. `UmlBrowserScript` pri aktiv치cii (zobrazen칤) prehliada캜a spust칤 funkciu
generovania diagramu v svg form치te a string posunie do prehliada캜a.

=== S칰visiace s칰bory

* `UnityProject/Assets/Scripts/Browser/UmlBrowserScript.cs`
* `UnityProject/Assets/Scripts/Browser/BrowsersManager.cs`
* `UnityProject/BrowserAssets/`
* `resources/scripts/app/main.lua`
* `resources/scripts/module/softviz/graph_handler.lua`